spring:
  application:
    name: restful-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fuauth